version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  
  web_server:
    build: .
    command: python3 /app/server.py
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "5000:5000"
    depends_on:
    - redis
    volumes:
      - .:/app
    