- name: Run message passing
  hosts: localhost
  become_user: root
  tasks:
  - name: Using pip install docker
    pip:
      name: docker
    become: True

  - name: Using pip install docker compose
    pip:
      name: docker-compose
    become: True

  - name: Run docker composer
    docker_compose:
      project_src: .